name = "mochi_examples"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mochi = { git = "https://github.com/qwexvf/mochi", ref = "main" }
mochi_websocket = { git = "https://github.com/qwexvf/mochi_websocket", ref = "main" }
