name = "mochi_http_server_example"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
wisp = ">= 1.0.0 and < 4.0.0"
mist = ">= 4.0.0 and < 9.0.0"
mochi = { git = "https://github.com/qwexvf/mochi", ref = "main" }
mochi_websocket = { git = "https://github.com/qwexvf/mochi_websocket", ref = "main" }
gleam_crypto = ">= 1.6.0 and < 2.0.0"
